<?php
/**
 * @file
 * Code for the Bibsdb Staff feature.
 */

include_once 'bibsdb_staff.features.inc';

/**
 * Implements hook_views_default_views_alter().
 *
 * We don't want to display a pager. Just show all items.
 */
function bibsdb_staff_views_default_views_alter(&$views) {
  if (!empty($views['ding_staff'])) {
	
			//dpm($views['ding_staff']->display['ding_staff_list_all']);
			$views['ding_staff']->display['default']->display_options['pager']['type'] = 'none';
			$views['ding_staff']->display['default']->display_options['pager']['options']['offset'] = '0';
			//$views['ding_staff']->display['ding_staff_list_all']->display_options['title'] = 'hallo';
      //$views['ding_staff']->display['ding_staff_list_all']->display_options['pager']['type'] = 'none';
      //$views['ding_staff']->display['ding_staff_list_all']->display_options['pager']['options']['offset'] = '0';
  }
  

}


/**
 * Implements hook_image_styles_alter().
 * Change ding_staff_thumbnail dimensions.
 * 
 * @param $styles
 */
function bibsdb_staff_image_styles_alter(&$styles) {

  if (function_exists('image_image_effect_info')) {
	  // Init the effect data.
   $effects = image_image_effect_info();
   $scale_effect = $effects['image_scale_and_crop'];
   $scale_effect['data'] = array();
   $scale_effect['weight'] = 0;

	  // Store styles data.
   $styles_data = array(
     'ding_staff_thumbnail' => array(
       'width' => 180,
       'height' => 240,
       ),
     );

   foreach ($styles_data as $style_name => $data) {
	    // Check that we only affect a default style.
     if ($styles[$style_name]['storage'] == IMAGE_STORAGE_DEFAULT) {
       $scale_effect['data'] = $data;
       $styles[$style_name]['effects'] = array();
       $styles[$style_name]['effects'][] = $scale_effect;
     }
   }
 }
}
