<?php
/**
 * @file
 * Code for the Bibsdb Staff feature.
 */

include_once 'bibsdb_staff.features.inc';

/**
 * Implements hook_views_default_views_alter().
 *
 * We don't want to display a teaser. Just show all items.
 */
function bibsdb_staff_views_default_views_alter(&$views) {
  if (!empty($views['ding_staff'])) {
	
			//dpm($views['ding_staff']->display['ding_staff_list_all']);
			//dpm($views['ding_staff']->display['ding_staff_list_all']);
			$views['ding_staff']->display['ding_staff_list_all']->display_options['title'] = 'hallo';
      $views['ding_staff']->display['ding_staff_list_all']->display_options['pager']['type'] = 'none';
      $views['ding_staff']->display['ding_staff_list_all']->display_options['pager']['options']['offset'] = '0';
  }
}
